name: 'Hello actin'
descriptin: 'Greet sonene'
author: 'foo@bar'

inputs:
  MY_NAME:
    descriptin: 'Who to greet'
    required: true
    default: 'World'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'mic'
  color: 'purple'

